name: Analyse Bitcoin Automatique

on:
  schedule:
    - cron: "0 * * * *"   # Toutes les heures
  workflow_dispatch:

jobs:
  run-analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: pip install -r requirements.txt
      - run: python analyse.py
      - name: Commit des résultats
        run: |
          git config --global user.name "auto-analyse"
          git config --global user.email "bot@example.com"
          git add data/*
          git commit -m "Mise à jour automatique des données Bitcoin" || exit 0
          git push